---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: snyk-container-demo
    app.kubernetes.io/name: snyk-container-demo
    app.kubernetes.io/version: "1.0"
  name: snyk-container-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: snyk-container-demo
    app.kubernetes.io/name: snyk-container-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-container-demo
  labels:
    app.kubernetes.io/instance: snyk-container-demo
    app.kubernetes.io/name: snyk-container-demo
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/instance: snyk-container-demo
        app.kubernetes.io/name: snyk-container-demo
  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: snyk-container-demo
        app.kubernetes.io/name: snyk-container-demo
    spec:
      containers:
        - name: snyk-container-demo
          image: snyk/snyk-container-demo
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP